version: '2'
services:
  findtheroad-springboot:
    build:
      context: .
    image: findtheroad-springboot
    container_name: findtheroad-springboot
    depends_on:
      - mongoFTR
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: findtheroad-springboot
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      #SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: true
      SPRING_DATA_MONGODB_HOST: mongoFTR
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: root
      SPRING_DATA_MONGODB_DATABASE: admin

  mongoFTR:
    image: mongo
    container_name: mongoFTR
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/log:/var/log/mongodb
